### ISSUE TITLE
Modules repeatedly   imported 

### ISSUE THREAD

**Issue by AliHaider20** [Stalence/erdos_neu#3]
Many modules are repeatedly imported which can increase time complexity. Plz have a look @Stalence .

**Comment by Stalence** [comment]
Yes will do. Thanks for that.

**Comment by AliHaider20** [comment]
You can accept my pull request.

**Comment by Stalence** [comment]
Thanks. I have more updates pending on the code but I haven't pushed them yet cause I need some time to review them.  I will update the repo again as soon as possible.

**Comment by AliHaider20** [comment]
Ok. Hey, I don't find my name in the contributor's list inside the insights tab.
